### ISSUE TITLE
render server response on frontend

### ISSUE THREAD

**Issue by hakanErgin** [HackYourFutureBelgium/class-5-project-lazyvariable#16]
an idea, if we don't have a better one; maybe we can start with rendering server response with the json object on our frontend.

-should we make a main route and view things there?

**Comment by prgrmfl** [comment]
We can make a route on backend for the ultimate result page we want to see, and on that route we can render response from server which would be whole json object for the first user?

**Comment by ramzisalem** [comment]
Sounds go to me, but firstly we should be done with the routes of our backend, right!

**Comment by hakanErgin** [comment]
I suppose we're not doing this. I'll close it
